spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pg-json
    username: pg-json
    password: pg-json
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: false
