name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'pom.xml'
      - '*.gradle'
      - 'src/**'
env:
  JAVA_VERSION: 17
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/*/gituhb/daggerok
          key: ${{ hashFiles('**/*.gradle', '**/pom.xml') }}-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./gradlew dependencies
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/*/gituhb/daggerok
          key: ${{ hashFiles('**/*.gradle', '**/pom.xml') }}-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./gradlew clean test
